from building import *

cwd     = GetCurrentDir()
src     = Split('''
components/newlib/locks.c
components/newlib/reent_init.c
components/newlib/syscall_table.c
components/newlib/syscalls.c
components/newlib/time.c
components/app_update/esp_ota_ops.c
components/driver/rtc_module.c
components/driver/i2c.c
components/driver/timer.c
components/driver/sdmmc_host.c
components/driver/sdmmc_transaction.c
components/driver/rmt.c
components/driver/pcnt.c
components/driver/gpio.c
components/driver/ledc.c
components/driver/periph_ctrl.c
components/driver/i2s.c
components/driver/uart.c
components/driver/sigmadelta.c
components/driver/spi_master.c
components/esp32/int_wdt.c
components/esp32/brownout.c
components/esp32/system_api.c
components/esp32/hw_random.c
components/esp32/cpu_freq.c
components/esp32/event_loop.c
components/esp32/core_dump.c
components/esp32/intr_alloc.c
components/esp32/ipc.c
components/esp32/freertos_hooks.c
components/esp32/heap_alloc_caps.c
components/esp32/deep_sleep.c
components/esp32/phy_init.c
components/esp32/crosscore_int.c
components/esp32/cpu_util.c
components/esp32/gdbstub.c
components/esp32/lib_printf.c
components/esp32/cpu_start.c
components/esp32/task_wdt.c
components/esp32/event_default_handlers.c
components/esp32/panic.c
components/esp32/hwcrypto/aes.c
components/esp32/hwcrypto/sha.c
components/ethernet/emac_main.c
components/ethernet/emac_dev.c
components/freertos/list.c
components/freertos/port.c
components/freertos/xtensa_init.c
components/freertos/croutine.c
components/freertos/xtensa_overlay_os_hook.c
components/freertos/xtensa_intr.c
components/freertos/libcpu.c
components/freertos/fmq.c
components/freertos/heap_regions.c
components/freertos/heap_regions_debug.c
components/freertos/ringbuf.c
components/json/library/cJSON.c
components/json/port/cJSON_Utils.c
components/log/log.c
components/micro-ecc/micro-ecc/uECC.c
components/sdmmc/sdmmc_cmd.c
components/spi_flash/flash_ops.c
components/spi_flash/cache_utils.c
components/spi_flash/spi_flash_rom_patch.c
components/spi_flash/partition.c
components/spi_flash/flash_mmap.c
components/tcpip_adapter/tcpip_adapter_lwip.c
components/ulp/ulp.c
components/wpa_supplicant/src/crypto/ms_funcs.c
components/wpa_supplicant/src/crypto/crypto_internal-modexp.c
components/wpa_supplicant/src/crypto/bignum.c
components/wpa_supplicant/src/crypto/sha1-pbkdf2.c
components/wpa_supplicant/src/crypto/md5.c
components/wpa_supplicant/src/crypto/rc4.c
components/wpa_supplicant/src/crypto/sha256.c
components/wpa_supplicant/src/crypto/dh_groups.c
components/wpa_supplicant/src/crypto/md4-internal.c
components/wpa_supplicant/src/crypto/sha1-internal.c
components/wpa_supplicant/src/crypto/aes-wrap.c
components/wpa_supplicant/src/crypto/crypto_internal.c
components/wpa_supplicant/src/crypto/dh_group5.c
components/wpa_supplicant/src/crypto/des-internal.c
components/wpa_supplicant/src/crypto/crypto_internal-rsa.c
components/wpa_supplicant/src/crypto/aes-unwrap.c
components/wpa_supplicant/src/crypto/aes-internal-dec.c
components/wpa_supplicant/src/crypto/sha1.c
components/wpa_supplicant/src/crypto/aes-internal.c
components/wpa_supplicant/src/crypto/md5-internal.c
components/wpa_supplicant/src/crypto/sha256-internal.c
components/wpa_supplicant/src/crypto/aes-internal-enc.c
components/wpa_supplicant/port/os_xtensa.c
components/xtensa-debug-module/trax.c
components/xtensa-debug-module/eri.c
''')

cpp_src = Split('''
components/cxx/cxx_guards.cpp
components/nvs_flash/src/nvs_api.cpp
components/nvs_flash/src/nvs_storage.cpp
components/nvs_flash/src/nvs_pagemanager.cpp
components/nvs_flash/src/nvs_item_hash_list.cpp
components/nvs_flash/src/nvs_page.cpp
components/nvs_flash/src/nvs_types.cpp
''')

asm_src = Split('''
components/freertos/./portasm.S
components/freertos/./xtensa_vectors.S
components/freertos/./xtensa_context.S
components/freertos/./xtensa_intr_asm.S
''')

CPPPATH = [
cwd + '/components/app_update/include',
cwd + '/components/bootloader_support/include',
cwd + '/components/bootloader_support/include_priv',
cwd + '/components/bt/include',
cwd + '/components/cxx/include',
cwd + '/components/driver/include',
cwd + '/components/driver/include/driver',
cwd + '/components/esp32',
cwd + '/components/esp32/include',
cwd + '/components/ethernet/include',
cwd + '/components/expat/port/include',
cwd + '/components/expat/include/expat',
cwd + '/components/fatfs/src',
cwd + '/components/freertos/include',
cwd + '/components/freertos/include/freertos',
cwd + '/components/json/include',
cwd + '/components/json/port/include',
cwd + '/components/log/include',
cwd + '/components/mdns/include',
cwd + '/components/micro-ecc/micro-ecc',
cwd + '/components/newlib/include',
cwd + '/components/newlib/platform_include',
cwd + '/components/nvs_flash/include',
cwd + '/components/sdmmc/include',
cwd + '/components/spi_flash/include',
cwd + '/components/tcpip_adapter/include',
cwd + '/components/ulp/include',
# cwd + '/components/vfs/include',
cwd + '/components/wpa_supplicant/include',
cwd + '/components/wpa_supplicant/port/include',
cwd + '/components/xtensa-debug-module/include',
]
CPPDEFINES = ['WITH_POSIX', 'ESP_PLATFORM']

group = DefineGroup('esp-idf', src + cpp_src + asm_src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

# group = group + SConscript('SConscript_mbedtls')
# group = group + SConscript('SConscript_nghttp2')
# group = group + SConscript('SConscript_openssl')
# group = group + SConscript('SConscript_coap')

group = group + SConscript('SConscript_esp32lib')
group = group + SConscript('SConscript_newlib')
group = group + SConscript('SConscript_lwip')

Return('group')
